# GitHub Sponsors funding options
github: rakhaviantoni

# Other funding options
# patreon: username
# open_collective: username
# ko_fi: username
# tidelift: npm/create-viant-app
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# otechie: username
# lfx_crowdfunding: project-name
# custom: ['https://paypal.me/username', 'https://www.buymeacoffee.com/username']