name: 🚀 Feature Request
description: Suggest a new feature or enhancement for Viant
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see
      placeholder: Describe the feature in one or two sentences...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        As a developer, I want to...
        So that I can...
        Currently, I have to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      options:
        - New Framework Support
        - New Template Features
        - CLI Improvements
        - Styling Options
        - Testing Features
        - Build Tools
        - Developer Experience
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature would be used
      placeholder: |
        Example CLI command:
        npm create viant-app my-app --new-feature

        Example output:
        ...
      render: bash
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: Describe alternative solutions you've thought about...
    validations:
      required: false

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you willing to help implement this feature?
      options:
        - label: I'm willing to submit a PR for this feature
          required: false
        - label: I can help with testing
          required: false
        - label: I can help with documentation
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information, mockups, or references
      placeholder: Add any other context, screenshots, or links here...
    validations:
      required: false